# Generated by Django 4.1.7 on 2023-03-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
