# Generated by Django 4.1.7 on 2023-03-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='photo',
        ),
    ]
