# Generated by Django 4.1.7 on 2023-03-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pre_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category', verbose_name='Категория'),
        ),
    ]
